Fix navigation on the header
alshedivat/al-folio pull request #2000
Opened 2023-12-17 11:52 UTC by GihanAyesh

When on page other than about; the title is shown as a clickable object. But when clicked nothing happens. Fixed this issue by redirecting to the main page.

2023-12-20 15:33 UTC, george-gca commented
Are you sure this is happening? Everything seems fine on the [template demo site](https://alshedivat.github.io/al-folio/).

2023-12-22 05:28 UTC, GihanAyesh commented
Yes this happened to me and two more friends. 

Reproduce steps: Deploy the page without docker (Didn't check with docker deployments don't think that's an issue)

2023-12-25 18:40 UTC, george-gca commented
I don't know if this is actually the problem. In the current solution, it generates `href="/al-folio/"`, which in turn creates the link `127.0.0.1:4000/al-folio/` that can be seen in the bottom left here:

![image](https://github.com/alshedivat/al-folio/assets/31376482/6f1c42f2-1123-4c7c-b1e4-1d831fe02734)

With your solution, it generates the whole url, which would be `href="http://localhost:4000/"`, creating the link `localhost:4000` as can be seen in the bottom left:

![image](https://github.com/alshedivat/al-folio/assets/31376482/d4033a25-d033-48d9-b7ac-fa4a163859ff)

Which leads to the wrong url and consequently to the `Page not found`.

2023-12-30 21:49 UTC, alshedivat requested changes
please prepend `url` instead of substituting `baseurl` with it and test if it works. happy to merge if that solves your problem.

2023-12-30 21:49 UTC, alshedivat commented on _includes/header.html
> +          <a class="navbar-brand title font-weight-lighter" href="{{ site.url }}/">
```suggestion
          <a class="navbar-brand title font-weight-lighter" href="{{ site.baseurl | prepend: site.url }}/">
```

2024-01-23 04:38 UTC, alshedivat commented
closing this since it will require a rebase and the change is just a one-liner. please rebase and reopen if still an issue.

2024-01-23 04:38 UTC, closed without merging