Fix: Add back-to-top button
alshedivat/al-folio pull request #2433
Opened 2024-05-22 06:07 UTC by abhilesh

Fixes #2425 

PR #2427 adds a back-to-top button, however the button overlaps with the footer when `footer_fixed: false` and [has inadequate spacing](https://github.com/alshedivat/al-folio/issues/2425#issuecomment-2121670658) with `footer_fixed: true` 

Changes in this PR:
- Fix positioning of button on fixed and sticky footer layouts 
- Add option to disable back-to-top button by setting `back_to_top: false` in `_config.yml`
- Add button transparency to avoid button blocking content view
- Reduce size of button

Demo - 

| Device | Fixed footer | Sticky footer |
| :-----------: | :-------------: | :-----------: |
|  Mobile | ![fixed_footer_mobile](https://github.com/alshedivat/al-folio/assets/2447878/2e17be04-1fa7-40c5-b691-829e92055367) |  ![sticky_footer_mobile](https://github.com/alshedivat/al-folio/assets/2447878/f5567e43-e6fe-442d-9a7f-99e0577e220b) |
| Desktop | ![fixed_footer_desktop](https://github.com/alshedivat/al-folio/assets/2447878/fc755839-841a-4e6b-b249-2c75bc552ad8) | ![sticky_footer_desktop](https://github.com/alshedivat/al-folio/assets/2447878/ef9a4c99-ce4c-4ac3-8fbb-207af9be245a) |

Miscellaneous change - Added personal website under `Academics` to `README.md`

2024-05-23 16:09 UTC, george-gca requested changes

2024-05-23 16:09 UTC, george-gca commented on _sass/_themes.scss
> +  --global-back-to-top-bg-color: rgba(#{red($white-color)}, #{green($white-color)}, #{blue($white-color)}, 0.5);
Same here `rgba($white-color, 0.5);`

2024-05-24 02:07 UTC, simonwei97 commented
`back-to-top` souce js file is [here](https://github.com/alshedivat/al-folio/blob/master/assets/js/vanilla-back-to-top.min.js), which target repo is https://github.com/vfeskov/vanilla-back-to-top.

2024-05-24 02:18 UTC, george-gca commented
Yes, but which changes were made to that file in your commit?

2024-05-24 06:06 UTC, abhilesh commented on _sass/_themes.scss
> +  --global-back-to-top-bg-color: rgba(#{red($black-color)}, #{green($black-color)}, #{blue($black-color)}, 0.4);
SASS variables don't seem directly compatible with the rgba() function, hence to apply transparency I have to extract the RGB components. 

The suggestion `rgba($black-color, 0.4)` results in this - 
<img width="724" alt="Screenshot 2024-05-24 at 07 02 36" src="https://github.com/alshedivat/al-folio/assets/2447878/6d13d455-5fef-405d-8322-de0239a8cfec">

2024-05-24 06:06 UTC, abhilesh commented on _sass/_themes.scss
> +  --global-back-to-top-bg-color: rgba(#{red($white-color)}, #{green($white-color)}, #{blue($white-color)}, 0.5);
Same here - 

<img width="1439" alt="Screenshot 2024-05-24 at 07 02 58" src="https://github.com/alshedivat/al-folio/assets/2447878/2335b705-8818-4e27-8733-9594b667987b">

2024-05-24 07:02 UTC, simonwei97 commented
> `back-to-top` souce js file #2425 is [here](https://github.com/alshedivat/al-folio/blob/master/assets/js/vanilla-back-to-top.min.js), which target repo is https://github.com/vfeskov/vanilla-back-to-top.

@abhilesh  Like what georage said in this code review, could you explain what do you change for this `back-to-top` js file? Adding transparency config?

2024-05-24 07:54 UTC, abhilesh commented on assets/js/vanilla-back-to-top.min.js
I added the following modifications to the already minified `vanilla-back-to-top.min.js` added to the repo in PR #2427 

Changed the dimensions of the button -
`o=Math.round(.43*E),t=Math.round(.29*E)` to `o=Math.round(.35*E),t=Math.round(.2*E)`

Added the following to ensure that the button stays on top of sticky or fixed footer - 

```js
window.addEventListener('load', function() {
    var button = document.getElementById('back-to-top');
    var stickyFooter = document.querySelector('.sticky-bottom');
    var fixedFooter = document.querySelector('.fixed-bottom');
  
    if (!button) {
      return;
    }
  
    window.addEventListener('scroll', function() {
      if (stickyFooter) {
        var stickyFooterRect = stickyFooter.getBoundingClientRect();
        if (window.scrollY + window.innerHeight > document.body.scrollHeight - stickyFooterRect.height) {
          button.style.position = 'fixed';
          button.style.bottom = (stickyFooterRect.height + 20) + 'px'; // 20 is the offset from the footer
        } else {
          button.style.position = 'fixed';
          button.style.bottom = '20px'; // original position
        }
      }
      
      if (fixedFooter) {
        var fixedFooterRect = fixedFooter.getBoundingClientRect();
        button.style.position = 'fixed';
        button.style.bottom = (fixedFooterRect.height + 20) + 'px'; // 20 is the offset from the footer
      }
    });
});
```

Briefly, 
- Get the button and footer elements upon website 'load'
- Upon 'scroll', get the position and size of the footer
- Check if footer visible on screen, if visible, fix the button's position to be 20px above footer.

I, then, minified the script again, just to be consistent with the previous PR #2427

2024-05-24 15:37 UTC, abhilesh reviewed
The changes suggested for specifying the colour variables for the button didn't work as expected (see attached screenshots) 

I elaborated on the changes made to the js file.
The original file committed in the previous PR was already minified (and hence a one-liner). I added the code specified, minified the file and committed to the PR. If needed, I can beautify the file and add it to the PR

2024-05-24 18:16 UTC, george-gca approved these changes

2024-05-24 18:58 UTC, merged