Fix: date pill position on CV
alshedivat/al-folio pull request #2455
Opened 2024-05-28 12:42 UTC by abhilesh

Fixes: #2393 

Changes made in this PR - 
Added `style="width: 75px; transform: translateX(-15px) translateY(-5px);">` to move the date pill `15px` to the left and `5px` to the top

| Before | After |
| :-----: | :----: |
| ![date_pill_before](https://github.com/alshedivat/al-folio/assets/2447878/be80f8ea-b41f-4013-ace2-2ce4b184f076) | ![date_pill_after](https://github.com/alshedivat/al-folio/assets/2447878/6f627e98-45aa-4b9a-b111-4c6c2013820c) |

2024-05-28 17:55 UTC, george-gca requested changes
Can you move all those csses from `style` attributes to `_sass/_base.scss`? Not sure if this would cause too much trouble, but this way one can change the whole behavior just by messing with css and not into the liquid files.

2024-05-28 18:25 UTC, CheariX commented
I'm a bit curious... Moving the pills "some" pixels left looks like a work around to me. 
Does anyone have an idea what is the root cause of this issue?

2024-05-29 07:50 UTC, abhilesh reviewed
Added a new class `date-column` to the liquid files and moved the styling options to `_sass/_base.scss`. I didn't notice any changes elsewhere.

2024-05-31 16:27 UTC, george-gca approved these changes

2024-05-31 16:27 UTC, merged