Add support for translatable/customizable section titles in the cv page
alshedivat/al-folio pull request #2543
Opened 2024-07-04 02:43 UTC by romanescherrer

This PR adds support for translating or customizing section title in the resume from the `_config.yaml`file. This feature enhances the internationalization of the al-folio theme, allowing users to customize the section titles without modifying the liquid template directly.

# Modification
- added a `sectiontitle`parameter in the `_config.yml`to store translations for section titles.
- Updated `cv.liquid` to use titles from `sectiontitle`if available, defaulting to the original section name if a translation is not provided.
- Updated the documentation in `CUSTOMIZE.md` to explain how to used this new feature.

# Example (in French)

```yaml
# _config.yml 
sectiontitles:
  basics: Informations personnelles
  work: experiences
  education: # Leave it blank for the default title
  publications:
  projects: projets
  volunteer:
  awards:
  certificates:
  skills: Compétences
  languages: langues
  interests: hobbits
  references:
```

2024-07-04 03:22 UTC, george-gca commented
For a version of al-folio with support for localization, I recommend [my fork of it](https://github.com/george-gca/multi-language-al-folio), which was created specifically for this.

2024-07-04 03:35 UTC, romanescherrer commented
@george-gca, thank you for sharing your impressive work. I'm considering using it for my website :). Nevertheless, I believe it's important to accommodate users who might want to customize the title sections on the CV page. For instance, some might prefer to change 'Basic' to 'Personal Informations' or translate it into another language.

2024-07-08 19:57 UTC, george-gca requested changes

2024-07-08 19:57 UTC, george-gca commented on _config.yml
> +sectiontitles:
I believe it's best to use `sections_titles` instead. `jsonresume` is only in a single word because it is the name of the library.

2024-07-08 19:57 UTC, george-gca commented on _config.yml
> +# Customize the section titles in the cv page, leave it blank for default
Add to this comment the info about it only being used when the cv is loaded from jsonr. Even though it is in that section in _config.yml, it's better to make it clear.

2024-07-08 20:00 UTC, george-gca commented
@alshedivat @pourmand1376 @arunoruto any thoughts on this PR?

2024-07-10 17:12 UTC, CheariX commented
My five cents: our `config.yml` is growing a lot. Do we really want to have so many config parameters in it? Wouldn't it be better to make it configurable on a per-site basis, e.g. in `cv.md`?

2024-07-10 17:47 UTC, george-gca commented
I agree with @CheariX. This would be better as an option in the page itself.

2024-10-20 02:14 UTC, closed without merging