Allow URLs in bib award field
alshedivat/al-folio pull request #2553
Opened 2024-07-09 15:40 UTC by sim642

If the `award` field in a bib entry is an URL, then link to it directly instead of opening an abstract-like text box.

2024-07-09 15:49 UTC, george-gca requested changes

2024-07-09 15:49 UTC, george-gca commented on _layouts/bib.liquid
> +        {% if entry.award contains '://' %}
What if the text someone wrote contains a link inside? Maybe it is best to check if the link in not a url with some other checks, for instance, if it doesn't start with one of `http`, `https`, `ftp` and doesn't contain any spaces.

2024-07-09 21:58 UTC, CheariX commented
Do we really want to handle this within the `award` field?
The example that @george-gca describes shows how much code complexity we must add to handle this.

Would it make sense to use a different field, like  `award_link`, for this use-case?

2024-07-10 06:15 UTC, sim642 commented
I can do that, but I just followed what's already common in al-folio: the `contains '://'` for determining if something is an URL or not.

2024-07-10 15:19 UTC, george-gca commented
Doing what @CheariX suggested makes sense, since it is more straightforward to understand what the field does. Adding a link from `award` itself seems almost like an easter egg.

2024-09-18 04:39 UTC, closed without merging