Encoded email in CV using jekyll-email-protect
alshedivat/al-folio pull request #2576
Opened 2024-07-15 06:57 UTC by tonideleo

I added a simple solution where the email provided in the json CV file can also be obfuscated using jekyll-email-protect. In the json file, the email field has now two entries, the first one being the email address and the second being the string to cover up the email.

2024-07-15 14:43 UTC, george-gca requested changes
1 - you forgot to add the gem to the commit
2 - is this solution still relevant? I mean, it seems a too simple substitution to be made to access the correct email again

2024-07-17 13:28 UTC, george-gca commented
It is not that I dislike it, it is more of a question (philosophical maybe?) in itself. With the evolution of all things in the internet, don't bots already handle this solution, since it is simple and apparently common?

2024-07-17 13:30 UTC, george-gca commented
> This solution applies similarly to the email button at the bottom pages.

Can you also add it there then?

2024-07-17 18:12 UTC, CheariX commented
Well.. I'm not convinced that this adds an level of protection. The Email is simply URL encoded, so calling `decodeURI("%61.%64...")` reveals your Email. I'm pretty sure that phishers are smart enough to handle this.

2024-07-18 14:24 UTC, closed without merging

2024-07-20 07:33 UTC, tonideleo commented
Fair point, I was just wondering because it was already used in the footer. Thanks for checking this out!