Added lightbox2 functionality complete with an example (project_10)
alshedivat/al-folio pull request #2692
Opened 2024-09-12 11:51 UTC by Picsiri

2024-09-12 15:37 UTC, george-gca commented
What is this for?

2024-09-13 03:28 UTC, Picsiri commented
What is a feature for? Anything you use it for.

I mostly needed it where I put 12 images in a row. With this you can actually see all of them. Also, in general I like if an image pops up when I click on it.

I am not sure about it but I guess imagemagick downscales the embedded images? In that case pop up does not enlarge the image but if you upload HD images...

2024-09-13 15:17 UTC, george-gca commented
> What is a feature for? Anything you use it for.

With this you assume we know what lightbox is for.

> I mostly needed it where I put 12 images in a row. With this you can actually see all of them. Also, in general I like if an image pops up when I click on it.

Do you have a working example or screenshots? In [this example](https://alshedivat.github.io/al-folio/blog/2015/images/) the zoomable images pops when you click on them.

> I am not sure about it but I guess imagemagick downscales the embedded images?

Not entirely sure, but I believe this is only currently happening on publication images like reported in #2668.

2024-09-28 15:17 UTC, Picsiri commented
Should I cancel the PR?

2024-10-20 02:18 UTC, alshedivat commented
just catching up here: what's the advantage of lightbox2 over zoomable images we already have?

2024-11-28 18:35 UTC, george-gca commented
Can you answer this @Picsiri?

2024-11-28 19:14 UTC, Picsiri commented
sorry, I don't usually check my GitHub ...

For example you can group images, there are more mini image setting options.

I made a pretty looking gallery with 6 images in a row that are unrecognizable on that scale but it is clearly indicated that they belong together and you can view them in a carousel.

2024-11-28 19:52 UTC, george-gca requested changes

2024-11-28 19:52 UTC, george-gca commented on _config.yml
I think this should be set per page, since not all pages may include images. So this should be, for example, in the project itself.

2024-11-28 19:52 UTC, george-gca commented on _includes/head.liquid
> +  <script src="{{ '/assets/js/lightbox-plus-jquery.min.js' | relative_url | bust_file_cache }}"></script>
Maybe this line and the next script tag should be included in [_includes/scripts/imageLayouts.liquid](https://github.com/alshedivat/al-folio/blob/main/_includes/scripts/imageLayouts.liquid) instead.

2024-11-28 19:52 UTC, george-gca commented on assets/js/lightbox-plus-jquery.min.js
We don't need the version with jquery, since we already include jquery in our code. Also, I think it would be better to include it from [jsdelivr](https://www.jsdelivr.com/package/npm/lightbox2), like we do with a lot of our js dependencies. Check, for example, how we include Leaflet in [_includes/scripts/leaflet.liquid](https://github.com/alshedivat/al-folio/blob/main/_includes/scripts/leaflet.liquid) and [_config.yml](https://github.com/alshedivat/al-folio/blob/b0d70d4dd6db8920aaddb0c2d0abcab15b85dc78/_config.yml#L527)

2024-12-01 23:00 UTC, Picsiri commented on assets/js/lightbox-plus-jquery.min.js
Thanks for checking it out. I will try to understand and complete the instructions.

2024-12-04 06:09 UTC, george-gca commented on assets/js/lightbox-plus-jquery.min.js
Would you mind if I create this initial part, then you further help me customize it? I can create the base functionality, then you create the options part. This way you can also create a single file for other gallery options I just found out about.

2024-12-05 19:23 UTC, george-gca commented on assets/js/lightbox-plus-jquery.min.js
@Picsiri check #2877.

2024-12-11 16:48 UTC, closed without merging