Added Jekyll-Archives (for tags, categories) and Jekyll site-map
alshedivat/al-folio pull request #346
Opened 2021-07-13 12:45 UTC by AbstractGeek

Additions:
1. Jekyll-sitemap so that a sitemap.xml is created automatically (with pdfs and files in assets being ignored).
2. Jekyll-Archives for tag, category and year-wise post display support (images below):
  - modified the blog/index.html to show tags, categories and years below the post-meta data.
  - added layout pages for tags, categories, years so that posts related to the tag/category/year can be shown in a page.
  - modified post metadata to show tags, categories and years.
  - changes in _sass/_base.scss to modified properties of the inserted html.
  - changes to individual posts to add tags and categories

Images:
<img width="610" alt="Screenshot 2021-07-13 at 6 10 19 PM" src="https://user-images.githubusercontent.com/12223207/125453586-88c2b59d-88a5-4342-821e-d2ef288ebac8.png">
<img width="705" alt="Screenshot 2021-07-13 at 6 18 44 PM" src="https://user-images.githubusercontent.com/12223207/125453606-8953ec36-e70f-47c0-98e5-f59580b3c0a7.png">
<img width="474" alt="Screenshot 2021-07-13 at 6 19 01 PM" src="https://user-images.githubusercontent.com/12223207/125453610-5138a6ce-c785-4321-b52d-c150d2bb637f.png">

2021-07-17 17:26 UTC, alshedivat requested changes
Looks amazing!! Thanks for your contribution.

It seems like `jekyll-sitemap` addition is a duplicate of #337. I'd prefer doing this in steps: first merge the sitemap PR, then rebase this one against updated master, and merge this one.

Also, left a few comments (mainly stylistic) throughout. Happy to merge once addressed.

2021-07-17 17:26 UTC, alshedivat commented on Gemfile
> +    gem 'github-pages'
I don't think `github-pages` gem is necessary.

2021-07-17 17:26 UTC, alshedivat commented on Gemfile
> +    gem 'jekyll-archives'
nit: please make sure all gems are listed in alphabetical order.

2021-07-17 17:26 UTC, alshedivat commented on Gemfile
> +    gem 'jekyll-archives'
I'm not able to build the website without `jekyll-sitemap` included in the Gemfile.

```suggestion
    gem 'jekyll-archives'
    gem 'jekyll-sitemap'
```

2021-07-17 17:26 UTC, alshedivat commented on _config.yml
> +  - jekyll-archives
nit: please make sure all jekyll plugins are listed in alphabetical order.

2021-07-17 17:26 UTC, alshedivat commented on _config.yml
> +    scope:
nit: please change to the following:
```suggestion
  - scope:
```

2021-07-17 17:26 UTC, alshedivat commented on _config.yml
> +  enabled: [year, tags, categories]
could you add a brief comment on how to enable/disable categories? if you users don't want to have any categories, is it sufficient to simply leave `enabled:` blank?

2021-07-17 17:26 UTC, alshedivat commented on _config.yml
> +    category: '/category/:name/'
let's change permalinks to `/blog/...` so that everything gets nested under `/blog/`.

2021-07-17 17:26 UTC, alshedivat commented on _layouts/category-archive.html
> +    </li>
do you mind changing this from a simple list to a table-like structure? basically, identical to how `news` are displayed on the about page.

2021-07-17 17:26 UTC, alshedivat commented on _layouts/tag-archive.html
> +    </li>
same comment as for category archive:
> do you mind changing this from a simple list to a table-like structure? basically, identical to how `news` are displayed on the about page.

2021-07-17 17:26 UTC, alshedivat commented on _layouts/year-archive.html
> +	  </li>
same comment as for category archive:
> do you mind changing this from a simple list to a table-like structure? basically, identical to how `news` are displayed on the about page.

2021-07-17 17:26 UTC, alshedivat commented on blog/index.html
> +    {% assign read_time = page.content | number_of_words | divided_by: 180 | plus: 1 %}
really like the read time feature!

```suggestion
    {% assign read_time = page.content | number_of_words: "auto" | divided_by: 180 | plus: 1 %}
```

2021-08-24 08:18 UTC, AbstractGeek commented
Hey! I got busy with something but I will get back to this soon. Your suggestions look good :)

2021-10-04 00:08 UTC, alshedivat commented
just a kind reminder about this PR :) thanks!

2021-10-04 12:37 UTC, AbstractGeek commented
Thanks for the reminder!  I will get to it this weekend. Sorry about the delay!

2021-10-30 20:57 UTC, alshedivat approved these changes

2021-10-30 20:58 UTC, merged